### ISSUE TITLE
image rotation

### ISSUE THREAD

**Issue by eroux** [buda-base/mirador#5]
As part of the new image workflow it would be useful to allow Mirador to rotate images when we indicate a rotation in the manifest. Currently there's a bug:

https://github.com/ProjectMirador/mirador/issues/2962

but it's possible to instruct OSD to rotate the image:

https://github.com/openseadragon/openseadragon/issues/1793

(the degree option in http://openseadragon.github.io/docs/OpenSeadragon.html#.Options IIRC)

there is an example manifest on

https://eroux.fr/manifest-180-selector.json

I think this entails two different things:
- [ ] rotating the image in the reading view
- [ ] rotating the image through OSD in the page view

**Comment by eroux** [comment]
P.S.: in order to test external manifests easily, I'm think we could have an URI option in the `/view/` route, like `https://library.bdrc.io/view/?manifest=https%3A//eroux.fr/manifest-180-selector.json`

**Comment by berger-n** [comment]
> I think this entails two different things:
> 
> * [ ]  rotating the image in the reading view
> * [ ]  rotating the image through OSD in the page view

regarding the second item, yesterday I randomly took a look at [bdr:W8LS76068](https://library.bdrc.io/view/bdr:W8LS76068) (in latest scans) and it happens it has both lanscape and portrait images, which you can already rotate as you wish in OSD:

![image](https://user-images.githubusercontent.com/33383857/123401236-df258e80-d5a6-11eb-8428-212e1a10ef0c.png)

but I guess you meant displaying the image with the correct orientation without the user intervention, both in reading & page view
let's have a look at it

**Comment by eroux** [comment]
ah yes excellent! Yes, the use case that corresponds to the issue is the first image of W1KG21720 which is upside down. The idea is to indicate that in the BVM thingy, then the information would be in the manifest, and then mirador would use it to rotate the image by default. This kind of workflow is much more efficient than changing the image on s3, which entails a lot of work on AO's side and takes time

**Comment by berger-n** [comment]
first step, there is now a manifest parameter in `/view` route: http://library-dev.bdrc.io/view/tmp:external?manifest=http://library-dev.bdrc.io/manifest-180-selector.json

![image](https://user-images.githubusercontent.com/33383857/123421651-6aaa1a00-d5bd-11eb-8460-b02d6a85ad05.png)

(note that it needs a few tweaks in https://eroux.fr/manifest-180-selector.json for it to work
namely putting `service` block at the root of `/images/resource` and not in `/images/resource/"full"`
\+ using url on `iiif` not `iiif-dev`)

**Comment by eroux** [comment]
ah ok for `iiif` vs. `iiif-dev`! But the `"full"` thing is actually the correct way to do that, see the second example in https://iiif.io/api/presentation/2.1/#segments

**Comment by berger-n** [comment]
ok thanks! 
let's fix `mirador` code instead then

**Comment by eroux** [comment]
yes unfortuately there's some tweaking to do in the core!

**Comment by berger-n** [comment]
updated http://library-dev.bdrc.io/view/tmp:external?manifest=http://library-dev.bdrc.io/manifest-180-selector.json
- OSD opens image with the rotation set in manifest if any
- reading view uses rotation from manifest (which work flawlessly for 180° or portrait displayed as lanscape, but is a bit more approximative as is for landscape displayed as portrait)

**Comment by eroux** [comment]
wow this is perfect!! thanks a lot! I think it's safe to deploy in prod right?

**Comment by eroux** [comment]
wait, I think http://library-dev.bdrc.io/manifest-180-selector.json in its current state is not correct:

```json
              "resource": {
                "@id": "https://iiif.bdrc.io/bdr:I8LS76071::I8LS760710009.jpg/full/max/0/default.jpg",
                "@type": "dctypes:Image",
                "service": {
                  "@context": "http://iiif.io/api/image/2/context.json",
                  "@id": "https://iiif.bdrc.io/bdr:I8LS76071::I8LS760710009.jpg",
                  "width": 2200,
                  "height": 3389,
                  "profile": "http://iiif.io/api/image/2/level0.json",
                  "protocol": "http://iiif.io/api/image"
                },
                "format": "image/jpeg",
                "width": 2200,
                "height": 3389,
                "selector": {
                  "@context": "http://iiif.io/api/annex/openannotation/context.json",
                  "@type": "iiif:ImageApiSelector",
                  "rotation": "90"
                }
              },
              "on": "https://iiifpres.bdrc.io/v:bdr:I8LS76071/canvas/I8LS760710009.jpg"
            }
          ],
          "width": 2200,
          "height": 3389
        }
```

should be

```
              "resource": {
                "@id": "https://iiif.bdrc.io/bdr:I8LS76071::I8LS760710009.jpg/full/max/0/default.jpg",
                "@type": "dctypes:Image",
                "service": {
                  "@context": "http://iiif.io/api/image/2/context.json",
                  "@id": "https://iiif.bdrc.io/bdr:I8LS76071::I8LS760710009.jpg",
                  "width": 2200,
                  "height": 3389,
                  "profile": "http://iiif.io/api/image/2/level0.json",
                  "protocol": "http://iiif.io/api/image"
                },
                "format": "image/jpeg",
                "width": 3389,
                "height": 2200,
                "selector": {
                  "@context": "http://iiif.io/api/annex/openannotation/context.json",
                  "@type": "iiif:ImageApiSelector",
                  "rotation": "90"
                }
              },
              "on": "https://iiifpres.bdrc.io/v:bdr:I8LS76071/canvas/I8LS760710009.jpg"
            }
          ],
          "width": 3389,
          "height": 2200
        }
```

(width and height switched in two places)

**Comment by berger-n** [comment]
must say I'm not sure if it's really right both to set a rotation flag to 90 degrees *and* invert width and height...
(and this is not because it seem to break everything here... :smile: )

**Comment by berger-n** [comment]
reading the manifest thoroughly I notice that in `service` the original width & height are used
so I guess that's how it work, width/height must be inverted wherever rotation is set and has an impact on it

**Comment by eroux** [comment]
so, here's how I think of it:
- the image service always has the width / height of the original image, because it represents the original image
- the canvas is the area on screen where the image is displayed, and has the appropriate width / height, in the case of a 90° rotation, switched width / height from the image

**Comment by berger-n** [comment]
made two distinct manifest:
- http://library-dev.bdrc.io/view/tmp:external?manifest=http://library-dev.bdrc.io/manifest-180-selector.json
- http://library-dev.bdrc.io/view/tmp:external?manifest=http://library-dev.bdrc.io/manifest-180-selector-2.json

the latter has a minor centering issue I have no clue how to fix for now:
(but it's already an improvement from previous version where images could overlap page caption)

![image](https://user-images.githubusercontent.com/33383857/123838976-e2a17880-d90c-11eb-9708-c01934584a27.png)

**Comment by eroux** [comment]
Ah, the centering issue is interesting indeed... no need to look at it now though, this is excellent!

Now here's an interesting issue that I didn't anticipate: the thumbnails. Basically IIIF presentation API doesn't really allow rotated thumbnails (or at least there's no specified way to do them), so instead of rotating a iiif service, I think I'll have thumbnails like this for manifests with a first page rotated:

```
  "thumbnail" : {
    "@id" : "https://iiif.bdrc.io/bdr:I4CZ75258::I4CZ752580003.jpg/full/max/180/default.jpg",
    "format" : "image/jpeg",
    "width" : 2550,
    "height" : 879
  },
```

Now... I could add a service:

```
  "thumbnail" : {
    "@id" : "https://iiif.bdrc.io/bdr:I4CZ75258::I4CZ752580003.jpg/full/max/180/default.jpg",
    "format" : "image/jpeg",
    "width" : 2550,
    "height" : 879,
    "service": {
        "@context": "http://iiif.io/api/image/2/context.json",
        "@id": "https://iiif.bdrc.io/bdr:I4CZ75258::I4CZ752580003.jpg",
        "width": 2550,
        "height": 786,
        "profile": "http://iiif.io/api/image/2/level0.json",
        "protocol": "http://iiif.io/api/image"
      }
  },
```

but I don't think I can add a selector to indicate the 180° rotation... so I think we're going to need to hack a little bit so that the rotation (indicated in the `@id` of the thumbnail) is taken into account... what do you think? what would be the most convenient? (also, we'll have to hack something for the thumbnails in BUDA more generally, but that will be for another day)

**Comment by berger-n** [comment]
regarding the thumbnails in OSD, I think it can work without modifying the manifest
(actually I manually disabled thumbnail rotation for now because it did not work with same css patch than in reading view)

but I'm not sure that was what you meant, this is about thumbnail in search etc. rather than in mirador?

**Comment by eroux** [comment]
oh I just meant in Mirador, I thought it was reading the thumbnail of the manifest but if it doesn't then no problem for now

**Comment by berger-n** [comment]
done: http://library-dev.bdrc.io/view/tmp:external?manifest=http://library-dev.bdrc.io/manifest-180-selector.json

![image](https://user-images.githubusercontent.com/33383857/123999002-56f21f80-d9d2-11eb-96b6-b5ca416426bf.png)


and finally I also found out how to center vertical images in reading view for this one: 
http://library-dev.bdrc.io/view/tmp:external?manifest=http://library-dev.bdrc.io/manifest-180-selector-2.json

![image](https://user-images.githubusercontent.com/33383857/123999173-80ab4680-d9d2-11eb-827f-776b2bafbe1d.png)

![image](https://user-images.githubusercontent.com/33383857/123999223-8f91f900-d9d2-11eb-85b8-11ee15efd87f.png)

**Comment by eroux** [comment]
ah, wonderful! so, if you're ready I think we can push this to prod, and then I'll create one manifest with a rotated image to see how the rest of PDL handles it

**Comment by berger-n** [comment]
ok! it's now deployed on library: https://library.bdrc.io/view/tmp:external?manifest=https://library.bdrc.io/manifest-180-selector.json

**Comment by eroux** [comment]
ok perfect! Let me create a manifest with a rotated cover page for W1KG21720 / I1KG21816

**Comment by eroux** [comment]
ok! here's the manifest: https://iiifpres.bdrc.io/v:bdr:I1KG21816/manifest

**Comment by eroux** [comment]
well, https://library.bdrc.io/show/bdr:I1KG21816 doesn't crash, that's a good start :) the thumbnail is still upside down though... now, once it will be fixed, there's still the problem of https://library.bdrc.io/search?q=%22mkha%27%20%27gro%20%27gro%20ba%20bzang%20mo%27i%20gsung%20rab%20rnam%20thar%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:hasOpen which I'm not really sure how to handle... I see a few options:

```ttl
bdr:W1KG21720 tmp:thumbnailIIIFService  <https://iiif.bdrc.io/bdr:I1KG21816::I1KG218160003.jpg#rotation=180> .
```


```ttl
bdr:W1KG21720 tmp:thumbnailIIIFSelected  <https://iiif.bdrc.io/bdr:I1KG21816::I1KG218160003.jpg/180/full/max/default.jpg> .
```

what do you think?

**Comment by berger-n** [comment]
interesting... https://library.bdrc.io/show/bdr:W1KG21720 is upside down but https://library.bdrc.io/show/bdr:I1KG21816 is ok (using the `/180/` route):

![image](https://user-images.githubusercontent.com/33383857/124108960-f3660180-da66-11eb-94af-98eff032c19e.png)

shouldn't be too hard to fix `bdr:W1KG21720` accordingly I think

regarding search results I guess second option could be really straightforward as it already works in https://library.bdrc.io/show/bdr:I1KG21816
![image](https://user-images.githubusercontent.com/33383857/124108865-d92c2380-da66-11eb-96f9-941e625321ca.png)

**Comment by eroux** [comment]
ah ok good! I think https://library.bdrc.io/show/bdr:W1KG21720 is upside down because it's using the `tmp:thumbnailIIIFService` property right?

Also, just to confirm, if we use 

```ttl
bdr:W1KG21720 tmp:thumbnailIIIFSelected  <https://iiif.bdrc.io/bdr:I1KG21816::I1KG218160003.jpg/180/full/max/default.jpg> .
```

we would still have to change the `max` to the appropriate size right?

**Comment by eroux** [comment]
I've updated the data with this new format, see http://purl.bdrc.io/resource/W1KG21720.ttl

**Comment by berger-n** [comment]
updated thumbnail urls so that rotated one is displayed anywhere:

- https://library.bdrc.io/show/bdr:WA1KG21720

![image](https://user-images.githubusercontent.com/33383857/124131998-a5f68e00-da80-11eb-9c64-ae25eaf35b17.png)

- https://library.bdrc.io/show/bdr:MW1KG21720

![image](https://user-images.githubusercontent.com/33383857/124132034-af7ff600-da80-11eb-9990-3479de7d0e53.png)

- https://library.bdrc.io/search?q=%22mkha%27%20%27gro%20%27gro%20ba%20bzang%20mo%27i%20gsung%20rab%20rnam%20thar%22~1&lg=bo-x-ewts&t=Instance&pg=1

![image](https://user-images.githubusercontent.com/33383857/124131818-72b3ff00-da80-11eb-8c64-99e42abcb994.png)

(regarding latter point, it seems that the [query](http://purl.bdrc.io/lib/instanceFacetGraph?LG_NAME=bo-x-ewts&L_NAME=%22mkha%27%20%27gro%20%27gro%20ba%20bzang%20mo%27i%20gsung%20rab%20rnam%20thar%22~1) itself returns that version has no image:

![image](https://user-images.githubusercontent.com/33383857/124131262-ea355e80-da7f-11eb-9bb4-95a68bd8ec27.png)

should we obviously override this when there actually is a thumbnail?)


now something that is not related to thumbnail rotation,
but regarding thumbnail size in version page, it works using url like https://iiif.bdrc.io/bdr:I1KG21816::I1KG218160003.jpg/full/!2000,150/180/default.jpg 
though it seems that resolution is not sufficient and the thumbnail shows some artefacts:

![image](https://user-images.githubusercontent.com/33383857/124132523-33d27900-da81-11eb-9ee2-c7e81fbed1d1.png)

which is not surprising considering it's displayed with a width of 145px though its original size is only 100x145 ([link](https://iiif.bdrc.io/bdr:I1KG21816::I1KG218160003.jpg/full/!2000,145/180/default.jpg))

I guess we just have to use same display as in results 
(full view of page with black background when scan has portrait ratio)
not sure what an other solution could be?

**Comment by eroux** [comment]
ah right, I see where the no image is coming from, I'll fix that now. Yes, let's use the same display as in other places. Excellent!

**Comment by berger-n** [comment]
ok thanks! looks better now: https://library.bdrc.io/show/bdr:MW1KG21720

![image](https://user-images.githubusercontent.com/33383857/124137145-b1988380-da85-11eb-8cce-265961335895.png)

**Comment by eroux** [comment]
indeed, perfect, thanks a lot!
